name: CICD
on: [push]
permissions:
  contents: write
jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
      
      - name: Install and Run Check Script  
        run: |                              
          yarn install                      
          yarn prettier --check ./source     
      
      - name: Build                        
        run: yarn build                    
      
      - name: Deploy                       
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public